# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hbstack/bigger-picture"

[[module.imports]]
path = "github.com/hbstack/bs-tooltip"

[params.hb.gallery]
paginate = 24
